var globals_defs =
[
    [ "a", "globals_defs.html", null ],
    [ "asse", "globals_defs_a.html", null ],
    [ "b", "globals_defs_b.html", null ],
    [ "bind", "globals_defs_b.html", null ],
    [ "c", "globals_defs_c.html", null ],
    [ "cref", "globals_defs_c.html", null ],
    [ "d", "globals_defs_d.html", null ],
    [ "h", "globals_defs_h.html", null ],
    [ "i", "globals_defs_i.html", null ],
    [ "l", "globals_defs_l.html", null ],
    [ "m", "globals_defs_m.html", null ],
    [ "o", "globals_defs_o.html", null ],
    [ "p", "globals_defs_p.html", null ],
    [ "q", "globals_defs_q.html", null ],
    [ "ref", "globals_defs_r.html", null ],
    [ "s", "globals_defs_s.html", null ],
    [ "sign", "globals_defs_s.html", null ],
    [ "t", "globals_defs_t.html", null ],
    [ "u", "globals_defs_u.html", null ],
    [ "v", "globals_defs_v.html", null ],
    [ "vsnp", "globals_defs_v.html", null ],
    [ "x", "globals_defs_x.html", null ]
];